name: 打包应用并上传阿里云

on: 
  push:
    branches:
      - master

jobs:
  build:
    # runs-on  指定job任务运行时所需的虚拟机环境
    runs-on: ubuntu-latest
    steps:
      # 获取源码
      - name: 迁出代码
        # 使用action库 actions/checkout 获取源码
        uses: actions/checkout@master

      # 安装node

      - name: 安装nodejs
        # 使用action库 actions/setup-node 安装node
        uses: actions/setup-node@v1
        with:
          node-version: 16.9.1
        
      # 安装依赖
      - name: 打包
        run: npm run build

      # 上传阿里云服务器
      - name: 发布到阿里云
        uses: easingthemes/ssh-deploy@2.1.1
        env:
          # 私钥
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          # scp参数
          ARGS: "-avzr --delete"
          # 原目录
          SOURCE: "dist"
          # 服务器ip
          REMOTE_HOST: "47.107.57.59"
          # 用户
          REMOTE_USER: "root"
          # 目标地址
          TARGET: "/project"